### ISSUE TITLE
react-native-navigation compatibility

### ISSUE THREAD

**Issue by djMax** [jamiebuilds/unstated-next#11]
...and the second thing I'm confused about (with both unstated and unstated-next) is how it integrates with something like react-native-navigation. The trick there is there is seemingly no "top level component" - they are switching it out somewhat frequently. [More detail in my issue on RNN](https://github.com/wix/react-native-navigation/issues/5081)

I don't want to lose the context/container state on those transitions, but it's unclear how to avoid that without a "store like" concept ala Redux. It feels like perhaps a weakness of RNN, but maybe I'm missing something about how contexts work and how to get the desired behavior?

**Comment by jamiebuilds** [comment]
Was your problem fixed in that other thread?

**Comment by djMax** [comment]
For unstated, yes. For unstated-next, no, but it probably could be. unstated works better for me because of the simpler provider side implementation.

**Comment by vishrayne** [comment]
I too faced the same issue, and had to fallback to `unstated` for the same reasons.

**Comment by jandog8990** [comment]
@djMax Can you explain how you got Unstated to work with RNN. I've been having a hell of a time trying to get the state in multiple containers.

I too want a central location (i.e. AppContainer) that manages a global state and is able to track and share all changes on all screens. I tried something like this to no avail:

`let App = () => (
  <Provider>
    <Subscribe to={[DataContainer]}>
      {(dataContainer: DataContainer) =>
        <StackNav dataContainer={dataContainer}/>
      }
    </Subscribe>
  </Provider>
)
export default App;
interface StackNavProps {
  dataContainer: DataContainer
}
class StackNav extends React.Component<StackNavProps, any> {
  stackNav = createStackNavigator({
    Home: { 
      screen: (props: HomeScreenProps) => 
        <HomeScreen 
          {...props} 
          dataContainer={this.props.dataContainer}/> 
    }
  );
  
  public render() {
    return <this.stackNav />
  }
}`

**Comment by jandog8990** [comment]
I got this to work whoever needs the answer just shoot me a tag, I'll get back to you unlike these dudes. SMH. Cmon people.

**Comment by vishrayne** [comment]
> I got this to work whoever needs the answer just shoot me a tag, I'll get back to you unlike these dudes. SMH. Cmon people.

@jandog8990  Sincere apologies, was in a really tight spot, for the last couple of days.

But looking at the piece of code you shared,
```
stackNav = createStackNavigator({
    Home: { 
      screen: (props: HomeScreenProps) => 
        <HomeScreen 
          {...props} 
          dataContainer={this.props.dataContainer}/> 
    }
  );
```
and AFAIK `createStackNavigator` API is part of react-navigation library right?. But you were asking for RNN which is a different library as far as i know. Please correct me if I'm wrong
