### ISSUE TITLE
Where does Provider come from?

### ISSUE THREAD

**Issue by djMax** [jamiebuilds/unstated-next#12]
The line below uses a Provider export from unstated-next, but it doesn't export that symbol. Does this work somehow?

https://github.com/jamiebuilds/unstated-next/blob/9d4cdf9a575661ca5cef1c4b7d9b947ba896812e/example/index.tsx#L27

**Comment by jamiebuilds** [comment]
Oops, just a mistake from an idea I was playing around with in a branch
