### ISSUE TITLE
Async initial state?

### ISSUE THREAD

**Issue by d0minikt** [jamiebuilds/unstated-next#24]
Is there any way of setting an initial value that is fetched asynchronously?

**Comment by jamiebuilds** [comment]
You could do something along the lines of this:

```js
function useValue(initialState = () => null) {
  let [value, setValue] = useState(null)
  useEffect(() => {
    Promise.resolve(initialState())
      .then(initState => setCount(count))
      .catch(err => ...)
  }, [])
  // ...
  return { value }
}
```

**Comment by d0minikt** [comment]
Thanks, this worked perfectly 👍

**Comment by AjaxSolutions** [comment]
This tip should be added to the doc

**Comment by jamiebuilds** [comment]
I don't want to bloat the documentation too much, these issues are a great place to search for specific use cases

**Comment by ardeaf** [comment]
Trying to use this pattern, I'm very unfamiliar with custom hooks and a newcomer to the library. Would this result in any race conditions? I keep reading that async stuff in useEffect can result in race conditions.
