### ISSUE TITLE
Use with Class components

### ISSUE THREAD

**Issue by eligao** [jamiebuilds/unstated-next#29]
I understand the hooks are not directly supported in Class components, however, in some cases, the global states from unstated-next are needed in Class components. 
Is there an elegant way of accessing the state instead of wrapping a Class component in another function component?

**Comment by shobokshy** [comment]
An option is to use an HOC component. Ex:
```
function withYourState(Component) {  
return function WrappedComponent(props) {
    const yourState = YourState.useContainer();
    return <Component {...props} yourState={yourState} />;
  }
}
```

Then in your class component:
```
class YourComponent extends React.Component {
  render(){
    const yourState = this.props.yourState;
    return <div></div>;
  }
}

export default withYourState(YourComponent);
```

**Comment by eligao** [comment]
Thanks for the code, but this is exactly what I said `wrapping a Class component in another function component`. 
I'm thinking if there are no other elegant ways, we could add some utility wrappers just like `Subscribe` in the original `unstated` to make this more reusable.

**Comment by uyeong** [comment]
Function component is not sillver bullet. We still use function component and class component appropriately. unstated-next also needs an API for class components.

**Comment by leonardojimenez** [comment]
AFAIK this is based on hooks for several reasons including performance, IMHO having a project with mixing of Class and functional components is not great approach, if developers prefer to stick to class components then I guess this implementation/solution should not be used, also I guess that in order to support similar functionality to unstated-next in class components there should be a separate implementation in a separate repo (+ npm package) to achieve that

**Comment by picardplaisimond** [comment]
This issue alone causes me a lot of problems. Especially in the world of server-side rendering where it is sometimes necessary to use classes. React Hooks functions cannot completely replace classes yet. I need to be able to access data from anywhere in the app.

However, I understand the direction of this project. I just had to support this issue. It's still a perfect solution for smaller projects !

**Comment by jonsmithers** [comment]
Couldn't one just re-implement `<Subscribe />` like the old unstated?

```javascript
function Subscribe(props) {
  const { to, children } = props;
  const containers = to.map(Container => Container.useContainer());
  return children(...containers);
}
```

```jsx
<Counter.Provider>
  <Subscribe to={[Counter]}>
    {counter => 
      <div>{counter.count}</div>
    }
  </Subscribe>
</Counter.Provider>
```

**Comment by leonardojimenez** [comment]
> Couldn't one just re-implement `<Subscribe />` like the old unstated?
> 
> ```js
> function Subscribe(props) {
>   const { to, children } = props;
>   const containers = to.map(Container => Container.useContainer());
>   return children(...containers);
> }
> ```
> 
> ```js-jsx
> <Counter.Provider>
>   <Subscribe to={[Counter]}>
>     {counter => 
>       <div>{counter.count}</div>
>     }
>   </Subscribe>
> </Counter.Provider>
> ```

@jonsmithers I guess what you are proposing to do/implement is:
https://www.npmjs.com/package/unstated

I guess that's ^ what others are asking for as well.

**Comment by theproj3ct** [comment]
with unstated i couldn't manage to change state inside **ComponentDidMount** unless i used a child element in Subscribe.

I wish we could use classes because i want to change state on initial render, not only events.

**Comment by jonsmithers** [comment]
@theproj3ct I know it's not what this thread is about, but I think a simple higher-order-component is a decently elegant solution.

```javascript
function subscribeAsProp(ClassComponent, to) {
  return (props) => {
    let containers = to.map(Container => Container.useContainer());
    containers = [...containers]; // copy to new array so even pure/memoized components rerender
    return (
      <ClassComponent
        {...props}
        unstated={containers}
      />
    );
  }
}

class MyClassComponent extends React.PureComponent {
  componentDidMount() {
    const { unstated } = this.props;
    const [ counter ] = unstated;
    console.log("I can access counter container", counter);
  }
  render() {
    const { unstated } = this.props;
    const [ counter ] = unstated;
    return (
      <div>{counter.count}</div>
    );
  }
}

export default subscribeAsProp(MyClassComponent, [Counter]);
```

**Comment by theproj3ct** [comment]
Thanks @jonsmithers i will try that and see

**Comment by dkershner6** [comment]
As an FYI, since I needed this functionality, I created a library to handle it: https://github.com/dkershner6/unstated-next-subscribe

Feel free to use/contribute as desired.

**Comment by jamiebuilds** [comment]
People seemed to have found some solutions in this thread, but it's not something I'm interested in having in core
