### ISSUE TITLE
[Question] Advantage of Unstated over Context

### ISSUE THREAD

**Issue by hypervillain** [jamiebuilds/unstated-next#33]
Hello guys,

Naive question, probably most suited for @jamiebuilds :

I'd be curious to hear some tangible arguments for using unstated-next over React context? 

Thanks!

**Comment by mykolav** [comment]
Hi, 
I'm &mdash; somewhat self-evidently &mdash; not @jamiebuilds.

But your question seems to be addressed in the [README.md](https://github.com/jamiebuilds/unstated-next/blob/master/README.md). 
Here's a relevant portion:

> [React context] is great, it's perfect, more people should write code like this.
> 
> But sometimes we all need a little bit more structure and intentional API design in order to get it consistently right.
> 
> By introducing the createContainer() function, you can think about your custom hooks as "containers" and have an API that's clear and prevents you from using it wrong.

**Comment by AjaxSolutions** [comment]
Is unstated-next better than this pattern?

https://twitter.com/brian_d_vaughn/status/1131683016399417345

**Comment by jamiebuilds** [comment]
Unstated Next is that exact pattern but wrapped up as a library for convenience and a better shared understanding. When you call `UnstatedNext.createContainer()` you are creating that "controller" component (which I just reused the name `Container.Provider`) and when you call `Container.useContainer()` you're effectively calling `useContext()`.

**Comment by hypervillain** [comment]
Thank you for your answers guys, after playing around with and without Unstated Next, I realized it was pretty convenient indeed
