### ISSUE TITLE
How to avoid Provider hell?

### ISSUE THREAD

**Issue by filipjnc** [jamiebuilds/unstated-next#42]
This is a very simple yet versatile state management solution with support for hooks - props for that.

I'd like to know whether there is a way to avoid the Provider hell:
```
<Store1.Provider>
  <Store2.Provider>
     <Store3.Provider>
       <App />
     </Store3.Provider>
  </Store2.Provider>
</Store1.Provider>
```
when all I want to do is:
```
<Provider stores=[Store1, Store2, Store3]>
  <App />
</Provider>
```

**Comment by AjaxSolutions** [comment]
See this...  [https://github.com/jamiebuilds/unstated-next/issues/35](url)
