### ISSUE TITLE
Status, relationship to unstated?

### ISSUE THREAD

**Issue by estaub** [jamiebuilds/unstated-next#6]
@basarat had [nice things to say](https://twitter.com/basarat/status/1125212195539652610), so I'm here.

Can you say something about the likely stability of this project, and best way to adopt it now?  I know it's only been public 5 days, and there are no releases or even tags.  For instance, is it best to fork for a while?  You might want to add this kind of guidance to the readme.  

Similar, but not as good im**v**ho: [outstated](https://github.com/yamalight/outstated/)

**Comment by jamiebuilds** [comment]
> and there are no releases or even tags

Oops, I never pushed after publishing. I'll fix that when I get home.

> best way to adopt it now? 

I published it as a separate package for three reasons:

- You can use it along `unstated` easily if you want to migrate incrementally
- I want to spend a few months to verify that it can fulfill all the needs of `unstated`
- It gives me the chance to create another major version of the previous API of `unstated`
  - Which may allow me to add a hooks API to `unstated` to possibly make migrating easier

In the future I will merge the project back in and publish it as the next major version of `unstated`

In terms of stability, this API really adds so little to React that you could probably codemod it away or even create your own fork of it if you wanted to. I would consider it as stable as you consider React. 

I hope that this API is enough for people, but if some motivating use case came up I would consider it. Probably only additive changes though. I don't think there's any need to remove anything
