### ISSUE TITLE
strange error 

### ISSUE THREAD

**Issue by charjac** [jamiebuilds/unstated-next#9]
I have a strange error when trying to export a container:

Exported variable 'ThemeProvider' has or is using name 'ContainerProviderProps' from external module

```tsx
import { useState } from 'react';
import { createContainer } from 'unstated-next';

function useTheme() {
  const [settings, setTheme] = useState<string>('default');

  return { settings, setTheme };
}

const { Provider: ThemeProvider, useContainer } = createContainer(useTheme);

export { ThemeProvider, useContainer };
```

maybe it is not due to this lib

**Comment by charjac** [comment]
fixed by removing the line "declaration": true from my tsconfig.json

**Comment by jamiebuilds** [comment]
Should be fixed by https://github.com/jamiebuilds/unstated-next/pull/7
